default: &default
  adapter: postgresql
  endcoding: unicode
  username: postgres
  password: 5550129piyuelo
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  ##timeout: 5000

development:
  <<: *default
  database: recipes_db
  username: postgres

test:
  <<: *default
  database:  recipes_test_db
  username: postgres

production:
  <<: *default
  database:  recipes_production_db
  username: postgres
  password: <%= ENV["BLOG_APP_DATABASE_PASSWORD"] %>
