# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  endcoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: Recipes_db
  adapter: postgresql
  username: postgres
  password: mosi24031994
  host: localhost
  port: 5432

test:
  <<: *default
  database:  Recipes_test_db
  adapter: postgresql
  username: postgres
  password: mosi24031994
  host: localhost
  port: 5432

production:
  <<: *default
  database:  Recipes_db
  username: Recipes_db
  password: <%= ENV["BLOG_APP_DATABASE_PASSWORD"] %>
